
version: '3.7'
services:
  movie-info-service:
    image: ${GROUP_ID}/movie.info.service:${SERVICE_VERSION:-latest}
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - "./docker-logs:/workspace/movie-info-service/logs"
      - "./mongo-db-status.sh:/usr/local/bin/mongo-db-status.sh"
    restart: on-failure
    user: root
#    entrypoint: [ "bash", "mongo-db-status.sh" ]
    environment:
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8080 -Dspring.profiles.active=dev-docker -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}

  movie-review-service:
    image: ${GROUP_ID}/movie.review.service:${SERVICE_VERSION:-latest}
    ports:
      - "8888:8888"
      - "5006:5006"
    volumes:
      - "./docker-logs:/workspace/movie-review-service/logs"
      - "./mongo-db-status.sh:/usr/local/bin/mongo-db-status.sh"
    restart: on-failure
    user: root
#    entrypoint: [ "bash", "mongo-db-status.sh" ]
    environment:
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8888 -Dspring.profiles.active=dev-docker -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}


  movies-service:
    image: ${GROUP_ID}/movies.service:${SERVICE_VERSION:-latest}
    ports:
      - "8082:8082"
      - "5008:5008"
    volumes:
      - "./docker-logs:/workspace/movie-review-service/logs"
      - "./mongo-db-status.sh:/usr/local/bin/mongo-db-status.sh"
    restart: on-failure
    user: root
#    entrypoint: [ "bash", "mongo-db-status.sh" ]
    environment:
      - "JAVA_OPTS=-Dapp.clients.scheme=http -Dserver.port=8082 -Dspring.profiles.active=dev-docker -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008 -Xms128m -Xmx256m"
    networks:
      - ${GLOBAL_NETWORK:-services}